
name: Maven Verify Lifecycle

on: 
  push:
    branches:
      - master
      
  pull_request:
  
  workflow_dispatch: # run manually when needed.
  
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Maven verify
        run: mvn -B -q verify
