# This is a basic workflow to help you get started with Actions

name: Release to Maven Central Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on a new release
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
      with:
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v4.1.0
      with:
        gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
        
    - name: Set version from tag
      run: mvn -B -q versions:set -DnewVersion=$GITHUB_REF_NAME --file pom.xml
      
    - name: Publish package
      run: mvn -B clean deploy -P release --file pom.xml
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

        
