# This is a basic workflow to help you get started with Actions

name: Release to Maven Central Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on a new release
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-key: GPG_SIGNING_KEY

    - name: Set version from tag
      run: mvn -B mvn versions:set -DnewVersion=$GITHUB_REF --file pom.xml

    - name: Verify
      run: mvn -B verify --file pom.xml
      
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      
    - name: Publish package
      run: mvn -B clean deploy -P release
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

        
